### ISSUE TITLE
📔  EPIC: Create basic site

### ISSUE THREAD

**Issue by ElenaMLopez** [ElenaMLopez/Cool-shopping-Redux#2]
### As a user 😄 :

- [x] I want to have a home page with a list of products, displayed on cards.

- [x] When a user clicks on a product card, they will see a detailed page with more information about the clicked product.

- [x]  On the page of product detail, must be a button or link,  to come back to the home page.

### As a developer 💻 :
- I want a test on each component, looking for its correct visualization and correct flow.
- I want services to separate business logic from representational logic.
- I want to have a good code, readable and like a prose code, with good names and easy to read.

### Extra info 💡 : 
- Create as many issues as you need. 
- Link these issues to this one filling the checkbox at each requirement in the user history.
- To close this issue, just update the main branch with the final work! 

Happy coding!!! 😸

**Comment by ElenaMLopez** [comment]
### As a user 😄 :

- [x] I want to have a home page with a list of products, displayed on cards: Issue #3 resolved at #4 

- [x] When a user clicks on a product card, they will see a detailed page with more information about the clicked product.

- [x]  On the page of product detail, must be a button or link,  to come back to the home page.

Happy coding!!! 😸
